name: WeChat Steps Auto Submit

on:
  schedule:
    # 北京时间 9:00, 14:00, 19:00 (UTC+8)
    - cron: '0 1 * * *'  # 早上9点 (UTC+8)
    - cron: '0 6 * * *'  # 下午2点 (UTC+8) 
    - cron: '0 11 * * *' # 晚上7点 (UTC+8)
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  submit-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run step submission
      id: submit
      env:
        WECHAT_ACCOUNTS: ${{ secrets.WECHAT_ACCOUNTS }}
      run: |
        # 直接运行并捕获输出
        OUTPUT=$(python wechat_steps.py 2>&1)
        echo "$OUTPUT"
        # 提取关键信息
        echo "SUMMARY<<EOF" >> $GITHUB_ENV
        echo "$OUTPUT" | grep -E "(微信步数提交报告|总账号|成功|失败|✅|❌|大号|小号|倩|吕|[0-9]+步)" | head -15 >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Debug Summary
      run: |
        echo "Summary content:"
        echo "$SUMMARY"
        
    - name: Send email notification
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python push.py "$SUMMARY"
        
    - name: Keep repository alive
      run: |
        python keep_alive.py